/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.1-26-gf309408874-20240329"
#endif /* AVUTIL_FFVERSION_H */
